---
- name: Primary AWS buckets and base infra (native modules)
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    aws_primary_region: ap-south-1
    aws_profile: default

    s3_data_lake_bucket: tenant-0011-bucket
    s3_model_bucket: tenant-0011-model-bucket
    s3_backup_bucket: tenant-0011-backup-bucket
    dynamodb_table: tenant-0011-ddb-table

    common_tags:
      Project: GENAI4SAAS
      Env: dev

    # cost knobs
    dl_noncurrent_keep_days: 7          # delete old versions fast
    abort_multipart_days: 7             # clean up failed uploads

  tasks:
    - name: Data lake bucket (versioned, encrypted, block public)
      amazon.aws.s3_bucket:
        name: "{{ s3_data_lake_bucket }}"
        region: "{{ aws_primary_region }}"
        profile: "{{ aws_profile }}"
        state: present
        versioning: true
        encryption: AES256            # SSE-S3 (no KMS cost)
        public_access:
          block_public_acls: true
          ignore_public_acls: true
          block_public_policy: true
          restrict_public_buckets: true
        tags: "{{ common_tags | combine({'Name': 'data-lake'}) }}"

    - name: Lifecycle for data lake (minimal-cost housekeeping)
      community.aws.s3_lifecycle:
        name: "{{ s3_data_lake_bucket }}"
        region: "{{ aws_primary_region }}"
        profile: "{{ aws_profile }}"
        state: present
        status: enabled
        noncurrent_version_expiration_days: "{{ dl_noncurrent_keep_days }}"
        abort_incomplete_multipart_upload_days: "{{ abort_multipart_days }}"

    - name: Model bucket (no versioning, encrypted, block public)
      amazon.aws.s3_bucket:
        name: "{{ s3_model_bucket }}"
        region: "{{ aws_primary_region }}"
        profile: "{{ aws_profile }}"
        state: present
        versioning: false
        encryption: AES256
        public_access:
          block_public_acls: true
          ignore_public_acls: true
          block_public_policy: true
          restrict_public_buckets: true
        tags: "{{ common_tags | combine({'Name': 'model'}) }}"

    - name: Backup bucket (dev minimal-cost no versioning)
      amazon.aws.s3_bucket:
        name: "{{ s3_backup_bucket }}"
        region: "{{ aws_primary_region }}"
        profile: "{{ aws_profile }}"
        state: present
        versioning: false
        encryption: AES256
        public_access:
          block_public_acls: true
          ignore_public_acls: true
          block_public_policy: true
          restrict_public_buckets: true
        tags: "{{ common_tags | combine({'Name': 'backup'}) }}"

    - name: DynamoDB table (PK=pk, SK=sk) on-demand
      community.aws.dynamodb_table:
        name: "{{ dynamodb_table }}"
        region: "{{ aws_primary_region }}"
        profile: "{{ aws_profile }}"
        hash_key_name: pk
        hash_key_type: STRING
        range_key_name: sk
        range_key_type: STRING
        billing_mode: PAY_PER_REQUEST
        wait: true
        tags: "{{ common_tags }}"
